#!/usr/bin/env python3
"""
食材新鲜度检测 - 轻量Web训练服务器
适配AX630C低内存，支持IP访问，REST API + 简单网页界面
"""

import os
import sys
import json
import time
import glob
import threading
import pandas as pd
import numpy as np
import serial
import serial.tools.list_ports
from datetime import datetime
from flask import Flask, request, jsonify, send_file, render_template_string

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, BatchNormalization, Dropout, Flatten, Dense
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

app = Flask(__name__)

# 全局状态
g_state = {
    "ser": None,
    "is_logging": False,
    "logging_thread": None,
    "csv_file": None,
    "csv_writer": None,
    "current_label": "",
    "data_dir": "sensor_data",
    "training": False,
    "last_result": None,
    "log": [],
    "timer_seconds": 0,
    "timer_start_time": 0,
    "auto_stop_timer": None
}

def add_log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    entry = f"[{ts}] {msg}"
    g_state["log"].append(entry)
    print(entry)
    if len(g_state["log"]) > 500:
        g_state["log"] = g_state["log"][-500:]

# ------------------- 工具函数 -------------------
def create_sliding_windows(X, y, window_size, step):
    n_samples, n_features = X.shape
    windows = []
    labels = []
    for i in range(0, n_samples - window_size + 1, step):
        window = X[i:i+window_size, :]
        windows.append(window)
        center_idx = i + window_size // 2
        labels.append(y[center_idx])
    return np.array(windows), np.array(labels)

def build_model(input_shape, num_classes, dropout_rate):
    seq_len = input_shape[0]
    model = Sequential()
    model.add(Conv1D(16, kernel_size=3, activation='relu', input_shape=input_shape))
    model.add(BatchNormalization())
    if seq_len > 5:
        model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(dropout_rate))
    
    model.add(Conv1D(32, kernel_size=2, activation='relu'))
    model.add(BatchNormalization())
    if seq_len > 10:
        model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(dropout_rate))
    
    model.add(Flatten())
    model.add(Dense(16, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(dropout_rate))
    model.add(Dense(num_classes, activation='softmax'))
    return model

def convert_to_tflite(model, output_path):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model = converter.convert()
    with open(output_path, 'wb') as f:
        f.write(tflite_model)
    return tflite_model

def tflite_to_c_array(tflite_model, output_header_path, array_name="g_food_freshness_model"):
    with open(output_header_path, 'w') as f:
        f.write("// Autogenerated by train_server.py\n");
        f.write("// DO NOT EDIT - generated from web training\n\n");
        f.write("#include <stddef.h>\n");
        f.write("#include <stdint.h>\n\n");
        f.write(f"const unsigned int {array_name}_size = {len(tflite_model)};\n");
        f.write(f"const unsigned char {array_name}[] = {{\n  ");
        bytes_per_line = 16;
        for i, byte in enumerate(tflite_model):
            f.write(f"0x{byte:02x}, ");
            if (i + 1) % bytes_per_line == 0:
                f.write("\n  ");
        if len(tflite_model) % bytes_per_line != 0:
            f.write("\n");
        f.write("};\n\n");
    return output_header_path

# ------------------- 串口采集 -------------------
def parse_block(lines):
    import re
    def extract(pattern):
        for line in lines:
            match = re.search(pattern, line)
            if match:
                return match.group(1).strip()
        return None

    odor = extract(r"Odor:\s+([\d\.]+)\s+ppm")
    hcho = extract(r"HCHO:\s+([\d\.]+)\s+ppm")
    co = extract(r"CO:\s+([\d\.]+)\s+ppm")
    voc = extract(r"VOC:\s+([\d\.]+)\s+ppm")
    co2 = extract(r"CO2:\s+(\d+)\s+ppm")
    timestamp = extract(r"发送端时间戳:\s+(\d+)\s+ms")

    if None in [odor, hcho, co, voc, co2, timestamp]:
        return None

    try:
        return [
            int(timestamp)//1000,
            float(odor),
            float(hcho),
            float(co),
            float(voc),
            int(co2),
            g_state["current_label"]
        ]
    except:
        return None

def check_auto_stop():
    """自动停止定时器"""
    while g_state["is_logging"] and g_state["timer_seconds"] > 0:
        if not g_state["is_logging"]:
            break  # 已经手动停止，直接退出
        elapsed = int(time.time() - g_state["timer_start_time"])
        remaining = g_state["timer_seconds"] - elapsed
        if remaining <= 0:
            add_log(f"⏰ 定时采集到时间，自动停止")
            g_state["is_logging"] = False
            if g_state["csv_file"]:
                g_state["csv_file"].close()
                g_state["csv_file"] = None
                g_state["csv_writer"] = None
            break
        time.sleep(1)
    if g_state["is_logging"] and g_state["csv_file"]:
        try:
            g_state["csv_file"].close()
        except:
            pass
        g_state["csv_file"] = None
        g_state["csv_writer"] = None

def logging_worker():
    block_lines = []
    inside_block = False
    first_block = True
    while g_state["is_logging"] and g_state["ser"] and g_state["ser"].is_open:
        try:
            raw = g_state["ser"].readline().decode('utf-8', errors='ignore').rstrip('\r\n')
            if not raw:
                continue
            add_log(f"📟 RAW: {raw}")

            if raw.startswith("========== 接收到传感器数据 =========="):
                block_lines = []
                inside_block = True
                if first_block:
                    add_log("✅ 收到第一组数据，开始计时")
                    g_state["timer_start_time"] = time.time()
                    first_block = False
                continue
            elif raw.startswith("======================================") and inside_block:
                record = parse_block(block_lines)
                if record and g_state["csv_writer"]:
                    g_state["csv_writer"].writerow(record)
                    g_state["csv_file"].flush()
                    if record:
                        add_log(f"记录样本: Odor={record[1]} HCHO={record[2]} CO={record[3]} VOC={record[4]} CO2={record[5]}")
                inside_block = False
                block_lines = []
                continue
            elif inside_block:
                block_lines.append(raw)

        except Exception as e:
            add_log(f"串口异常: {str(e)}")
            break

# ------------------- API路由 -------------------
@app.route('/')
def index():
    html = '''
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>食材新鲜度检测 - Web训练</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 20px auto; padding: 0 20px; }
        h1 { color: #333; margin-bottom: 20px; }
        .card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; margin-bottom: 15px; }
        .row { display: flex; flex-wrap: wrap; gap: 15px; margin-bottom: 10px; align-items: center; }
        .col { flex: 1; min-width: 200px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; }
        input, select, button { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
        button { background: #4CAF50; color: white; border: none; cursor: pointer; font-size: 16px; }
        button:hover { background: #45a049; }
        button:disabled { background: #cccccc; cursor: not-allowed; }
        .danger { background: #f44336; }
        .danger:hover { background: #d32f2f; }
        #log { background: #f5f5f5; padding: 10px; border-radius: 4px; height: 300px; overflow-y: auto; font-family: monospace; font-size: 12px; }
        .log-entry { margin: 2px 0; }
        .success { color: green; }
        .error { color: red; }
        .data { color: blue; }
        #status { padding: 10px; border-radius: 4px; margin-bottom: 10px; }
        .status-disconnected { background: #ffebee; }
        .status-connected { background: #e8f5e9; }
        .status-logging { background: #fff3e0; }
        .status-training { background: #e3f2fd; }
        #timer { font-weight: bold; font-size: 18px; color: #d32f2f; text-align: center; }
    </style>
</head>
<body>
    <h1>🥦 食材新鲜度检测 - Web训练工具</h1>
    
    <div id="status" class="status-disconnected">状态: 未连接</div>
    <div class="row" style="justify-content: center;">
        <div id="timer" style="display: none;">剩余时间: --:--</div>
    </div>

    <div class="card">
        <h3>串口连接</h3>
        <div class="row">
            <div class="col">
                <label>串口号</label>
                <select id="port"></select>
            </div>
            <div class="col">
                <label>波特率</label>
                <select id="baud">
                    <option value="9600">9600</option>
                    <option value="115200" selected>115200</option>
                    <option value="230400">230400</option>
                </select>
            </div>
            <div class="col" style="flex: 0 0 120px; margin-top: 23px;">
                <button id="btn-refresh">刷新</button>
            </div>
            <div class="col" style="flex: 0 0 120px; margin-top: 23px;">
                <button id="btn-connect">连接</button>
            </div>
        </div>
    </div>

    <div class="card">
        <h3>数据采集</h3>
        <div class="row">
            <div class="col">
                <label>标签 (如: apple_fresh)</label>
                <input id="label" type="text" value="apple_fresh">
            </div>
            <div class="col">
                <label>采集频率 (秒)</label>
                <input id="interval" type="number" min="1" max="60" value="5">
            </div>
            <div class="col">
                <label>自动停止 (分钟, 0=不停止)</label>
                <input id="auto_stop_minutes" type="number" min="0" max="120" value="10">
            </div>
            <div class="col" style="flex: 0 0 120px; margin-top: 23px;">
                <button id="btn-sync-interval">同步频率</button>
            </div>
        </div>
        <div class="row">
            <div class="col" style="flex: 0 0 150px; margin-top: 8px;">
                <button id="btn-start-log">开始采集</button>
            </div>
            <div class="col" style="flex: 0 0 150px; margin-top: 8px;">
                <button id="btn-stop-log" class="danger">停止采集</button>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p><b>说明:</b> 每个标签单独保存一个CSV文件，放在sensor_data/目录下</p>
            </div>
        </div>
    </div>

    <div class="card">
        <h3>训练参数</h3>
        <div class="row">
            <div class="col">
                <label>滑动窗口大小 (帧数)</label>
                <input id="window_size" type="number" min="1" max="20" value="5">
            </div>
            <div class="col">
                <label>滑动步长 (帧数)</label>
                <input id="window_step" type="number" min="1" max="10" value="2">
            </div>
            <div class="col">
                <label>训练轮数</label>
                <input id="epochs" type="number" min="10" max="300" value="100">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label>批次大小</label>
                <input id="batch_size" type="number" min="8" max="128" value="32">
            </div>
            <div class="col">
                <label>学习率</label>
                <input id="learning_rate" type="number" step="0.0001" min="0.0001" max="0.01" value="0.001">
            </div>
            <div class="col">
                <label>Dropout</label>
                <input id="dropout" type="number" step="0.05" min="0.1" max="0.5" value="0.2">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label>输出模型名</label>
                <input id="output_name" type="text" value="food_freshness">
            </div>
            <div class="col" style="flex: 0 0 150px; margin-top: 23px;">
                <button id="btn-start-train">开始训练</button>
            </div>
        </div>
    </div>

    <div class="card">
        <h3>下载结果</h3>
        <div class="row">
            <div class="col" style="flex: 0 0 150px;">
                <button id="btn-download-h">下载头文件 (.h)</button>
            </div>
            <div class="col" style="flex: 0 0 150px;">
                <button id="btn-download-tflite">下载TFLite (.tflite)</button>
            </div>
        </div>
    </div>

    <div class="card">
        <h3>日志</h3>
        <div id="log"></div>
    </div>

    <script>
        let state = {
            connected: false,
            logging: false,
            training: false,
            timer_seconds: 0,
            timer_interval: null
        };

        function formatTime(seconds) {
            let m = Math.floor(seconds / 60);
            let s = seconds % 60;
            return String(m).padStart(2, '0') + ":" + String(s).padStart(2, '0');
        }

        function updateTimerDisplay() {
            if (!state.logging || state.timer_seconds <= 0) {
                document.getElementById('timer').style.display = 'none';
                return;
            }
            document.getElementById('timer').style.display = 'block';
            let elapsed = Math.floor(Date.now() / 1000 - (window.timerStartTime || 0));
            let remaining = state.timer_seconds - elapsed;
            if (remaining < 0) remaining = 0;
            document.getElementById('timer').textContent = "剩余时间: " + formatTime(remaining);
        }

        function updateStatus() {
            let statusEl = document.getElementById('status');
            if (!state.connected) {
                statusEl.className = 'status-disconnected';
                statusEl.textContent = '状态: 未连接';
            } else if (state.logging) {
                statusEl.className = 'status-logging';
                statusEl.textContent = '状态: 采集中';
            } else if (state.training) {
                statusEl.className = 'status-training';
                statusEl.textContent = '状态: 训练中';
            } else {
                statusEl.className = 'status-connected';
                statusEl.textContent = '状态: 已连接，就绪';
            }
            document.getElementById('btn-start-log').disabled = !state.connected || state.logging || state.training;
            document.getElementById('btn-stop-log').disabled = !state.logging;
            document.getElementById('btn-start-train').disabled = state.logging || state.training;
            document.getElementById('btn-connect').disabled = state.connected;
            updateTimerDisplay();
        }

        async function refreshPorts() {
            let res = await fetch('/api/ports');
            let data = await res.json();
            let select = document.getElementById('port');
            select.innerHTML = '';
            data.ports.forEach(p => {
                let opt = document.createElement('option');
                opt.value = p;
                opt.textContent = p;
                select.appendChild(opt);
            });
        }

        async function connect() {
            let port = document.getElementById('port').value;
            let baud = parseInt(document.getElementById('baud').value);
            let res = await fetch('/api/connect', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({port, baud})
            });
            let data = await res.json();
            if (data.success) {
                state.connected = true;
                let interval = parseInt(document.getElementById('interval').value);
                await syncInterval();
            } else {
                alert('连接失败: ' + data.error);
            }
            updateStatus();
            refreshLog();
        }

        async function syncInterval() {
            let interval = parseInt(document.getElementById('interval').value);
            let res = await fetch('/api/sync_interval', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({interval})
            });
            let data = await res.json();
            refreshLog();
        }

        async function startLog() {
            let label = document.getElementById('label').value.trim();
            let autoMinutes = parseFloat(document.getElementById('auto_stop_minutes').value || 0);
            let interval = parseInt(document.getElementById('interval').value || 5);
            if (!label) {
                alert('请填写标签');
                return;
            }
            let res = await fetch('/api/start_log', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({
                    label,
                    interval,
                    data_dir: 'sensor_data',
                    auto_stop_minutes: autoMinutes
                })
            });
            let data = await res.json();
            if (data.success) {
                state.logging = true;
                state.timer_seconds = autoMinutes > 0 ? autoMinutes * 60 : 0;
                window.timerStartTime = Date.now() / 1000;
                if (state.timer_seconds > 0) {
                    state.timer_interval = setInterval(updateTimerDisplay, 1000);
                }
            } else {
                alert('开始失败: ' + data.error);
            }
            updateStatus();
            refreshLog();
        }

        async function stopLog() {
            if (state.timer_interval) {
                clearInterval(state.timer_interval);
                state.timer_interval = null;
            }
            let res = await fetch('/api/stop_log', {method: 'POST'});
            let data = await res.json();
            state.logging = false;
            state.timer_seconds = 0;
            updateStatus();
            refreshLog();
        }

        async function startTrain() {
            let params = {
                window_size: parseInt(document.getElementById('window_size').value),
                window_step: parseInt(document.getElementById('window_step').value),
                epochs: parseInt(document.getElementById('epochs').value),
                batch_size: parseInt(document.getElementById('batch_size').value),
                learning_rate: parseFloat(document.getElementById('learning_rate').value),
                dropout: parseFloat(document.getElementById('dropout').value),
                output_name: document.getElementById('output_name').value.trim(),
                data_dir: 'sensor_data'
            };
            if (!params.output_name) {
                alert('请填写输出模型名');
                return;
            }
            let res = await fetch('/api/train', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(params)
            });
            let data = await res.json();
            if (data.success) {
                state.training = true;
                updateStatus();
            } else {
                alert('启动失败: ' + data.error);
            }
            updateStatus();
            refreshLog();
        }

        function refreshLog() {
            fetch('/api/log').then(res => res.json()).then(data => {
                let logEl = document.getElementById('log');
                logEl.innerHTML = '';
                data.log.forEach(entry => {
                    let div = document.createElement('div');
                    div.className = 'log-entry';
                    div.textContent = entry;
                    if (entry.includes('✅')) div.classList.add('success');
                    if (entry.includes('❌')) div.classList.add('error');
                    if (entry.includes('📟')) div.classList.add('data');
                    logEl.appendChild(div);
                });
                logEl.scrollTop = logEl.scrollHeight;
            });
        }

        function downloadFile(path) {
            window.location.href = '/api/download?path=' + encodeURIComponent(path);
        }

        // 事件绑定
        document.getElementById('btn-refresh').onclick = refreshPorts;
        document.getElementById('btn-connect').onclick = connect;
        document.getElementById('btn-sync-interval').onclick = syncInterval;
        document.getElementById('btn-start-log').onclick = startLog;
        document.getElementById('btn-stop-log').onclick = stopLog;
        document.getElementById('btn-start-train').onclick = startTrain;
        document.getElementById('btn-download-h').onclick = () => {
            let name = document.getElementById('output_name').value.trim() || 'food_freshness';
            downloadFile(name + '.h');
        };
        document.getElementById('btn-download-tflite').onclick = () => {
            let name = document.getElementById('output_name').value.trim() || 'food_freshness';
            downloadFile(name + '.tflite');
        };

        // 初始化
        refreshPorts();
        refreshLog();
        updateStatus();

        // 定时刷新
        setInterval(() => {
            refreshLog();
            if (state.training) {
                fetch('/api/status').then(res => res.json()).then(data => {
                    state.training = data.training;
                    updateStatus();
                });
            }
            if (state.logging) {
                updateTimerDisplay();
            }
        }, 2000);
    </script>
</body>
</html>
    '''
    return render_template_string(html)

@app.route('/api/ports')
def api_ports():
    ports = serial.tools.list_ports.comports()
    port_list = [p.device for p in ports]
    return jsonify({"ports": port_list})

@app.route('/api/connect', methods=['POST'])
def api_connect():
    data = request.get_json()
    port = data['port']
    baud = int(data['baud'])
    try:
        g_state["ser"] = serial.Serial(port, baud, timeout=1)
        add_log(f"✅ 成功连接 {port} @ {baud} baud")
        return jsonify({"success": True})
    except Exception as e:
        add_log(f"❌ 连接失败: {str(e)}")
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/sync_interval', methods=['POST'])
def api_sync_interval():
    data = request.get_json()
    interval = int(data['interval'])
    if not g_state["ser"] or not g_state["ser"].is_open:
        add_log("❌ 串口未连接")
        return jsonify({"success": False, "error": "not connected"})
    cmd = f"set interval {interval}\n"
    g_state["ser"].write(cmd.encode())
    add_log(f"✅ 同步采集间隔: {interval} 秒")
    return jsonify({"success": True})

@app.route('/api/start_log', methods=['POST'])
def api_start_log():
    data = request.get_json()
    label = data['label']
    data_dir = data.get('data_dir', 'sensor_data')
    auto_stop_minutes = float(data.get('auto_stop_minutes', 0))
    interval = int(data.get('interval', 5))
    g_state["data_dir"] = data_dir
    if not g_state["ser"] or not g_state["ser"].is_open:
        add_log("❌ 串口未连接")
        return jsonify({"success": False, "error": "not connected"})
    if not label:
        add_log("❌ 标签为空")
        return jsonify({"success": False, "error": "empty label"})
    
    # 开始采集前清空串口输入缓冲区，避免残留旧数据一次性爆发读出
    g_state["ser"].reset_input_buffer()
    add_log("✅ 已清空串口输入缓冲区，避免残留旧数据")

    # 开始采集时只发送一次频率命令，避免频繁发送导致爆发
    if interval >= 2:
        cmd = f"set interval {interval}\n"
        g_state["ser"].write(cmd.encode())
        add_log(f"✅ 同步采集频率: {interval} 秒 → {cmd.strip()}")

    os.makedirs(data_dir, exist_ok=True)
    start_str = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = os.path.join(data_dir, f'{label}_{start_str}.csv')
    try:
        import csv
        g_state["csv_file"] = open(filename, 'w', newline='', encoding='utf-8-sig')
        g_state["csv_writer"] = csv.writer(g_state["csv_file"])
        header = ['Time_s', 'Odor', 'HCHO', 'CO', 'VOC', 'CO2', 'Label']
        g_state["csv_writer"].writerow(header)
        g_state["csv_file"].flush()
    except Exception as e:
        add_log(f"❌ 创建文件失败: {str(e)}")
        return jsonify({"success": False, "error": str(e)})
    
    g_state["current_label"] = label
    g_state["is_logging"] = True
    g_state["timer_seconds"] = int(auto_stop_minutes * 60) if auto_stop_minutes > 0 else 0
    g_state["timer_start_time"] = time.time()
    g_state["logging_thread"] = threading.Thread(target=logging_worker, daemon=True)
    g_state["logging_thread"].start()
    # 启动自动停止线程
    if auto_stop_minutes > 0:
        g_state["auto_stop_timer"] = threading.Thread(target=check_auto_stop, daemon=True)
        g_state["auto_stop_timer"].start()
        add_log(f"⏰ 自动停止设置: {auto_stop_minutes} 分钟，第一组数据到达后开始计时")
    add_log(f"✅ 开始采集，标签: {label}, 文件: {filename}（每个标签单独CSV）")
    return jsonify({"success": True})

@app.route('/api/stop_log', methods=['POST'])
def api_stop_log():
    g_state["is_logging"] = False
    if g_state["csv_file"]:
        try:
            g_state["csv_file"].close()
        except:
            pass
        g_state["csv_file"] = None
        g_state["csv_writer"] = None
    add_log("✅ 采集已停止")
    return jsonify({"success": True})

@app.route('/api/status')
def api_status():
    return jsonify({
        "connected": g_state["ser"] is not None and g_state["ser"].is_open,
        "logging": g_state["is_logging"],
        "training": g_state["training"]
    })

@app.route('/api/log')
def api_log():
    return jsonify({"log": g_state["log"]})

@app.route('/api/download')
def api_download():
    path = request.args.get('path', '')
    if not os.path.exists(path):
        return jsonify({"error": "file not found"}), 404
    return send_file(path, as_attachment=True)

def training_worker(params):
    try:
        g_state["training"] = True
        add_log("="*60)
        add_log("开始训练...")
        data_dir = params.get('data_dir', 'sensor_data')
        csv_files = glob.glob(os.path.join(data_dir, '*.csv'))
        add_log(f"数据目录: {data_dir}, 找到 {len(csv_files)} 个CSV文件")
        
        if len(csv_files) == 0:
            add_log("❌ 没有找到CSV文件，请先采集数据")
            g_state["training"] = False
            return
        
        # 加载所有CSV（多个标签分文件存储，这里合并训练）
        all_dfs = []
        for f in csv_files:
            add_log(f"  加载 {os.path.basename(f)}")
            df = pd.read_csv(f)
            all_dfs.append(df)
        df = pd.concat(all_dfs, ignore_index=True)
        add_log(f"总共 {len(df)} 条原始样本")

        # 提取特征标签
        feature_cols = ['Odor', 'HCHO', 'CO', 'VOC', 'CO2']
        X_raw = df[feature_cols].values
        labels_raw = df['Label'].values
        unique_labels = sorted(list(set(labels_raw)))
        label_to_idx = {l:i for i,l in enumerate(unique_labels)}
        y_raw = np.array([label_to_idx[l] for l in labels_raw])

        add_log(f"\n类别列表 ({len(unique_labels)} 类):")
        for l,i in label_to_idx.items():
            add_log(f"  [{i}] {l}")

        # 滑动窗口
        ws = params['window_size']
        step = params['window_step']
        if ws > 1:
            X_window, y_window = create_sliding_windows(X_raw, y_raw, ws, step)
            add_log(f"\n滑动窗口: 大小={ws}, 步长={step}, 生成 {X_window.shape[0]} 样本")
        else:
            X_window = X_raw[:, np.newaxis, :]
            y_window = y_raw

        # 标准化
        n_features = X_window.shape[-1]
        scaler = StandardScaler()
        X_reshaped = X_window.reshape(-1, n_features)
        X_scaled_reshaped = scaler.fit_transform(X_reshaped)
        X = X_scaled_reshaped.reshape(X_window.shape)

        # 划分
        X_train, X_test, y_train, y_test = train_test_split(
            X, y_window, test_size=0.2, random_state=42, stratify=y_window
        )
        add_log(f"\n训练集: {X_train.shape[0]} 样本")
        add_log(f"测试集: {X_test.shape[0]} 样本")

        # 构建模型
        num_classes = len(unique_labels)
        model = build_model(X.shape[1:], num_classes, params['dropout'])
        model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=params['learning_rate']),
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
        )

        early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        add_log("\n开始训练...")

        history = model.fit(
            X_train, y_train,
            batch_size=params['batch_size'],
            epochs=params['epochs'],
            validation_split=0.1,
            callbacks=[early_stop],
            verbose=0
        )

        test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
        add_log(f"\n训练完成，测试准确率: {test_acc:.4f}")

        y_pred = model.predict(X_test, verbose=0)
        y_pred_classes = np.argmax(y_pred, axis=1)
        report = classification_report(y_test, y_pred_classes, target_names=unique_labels)
        add_log("\n分类报告:")
        for line in report.split('\n'):
            if line.strip():
                add_log(line)

        # 导出
        output_base = params['output_name']
        tflite_path = f"{output_base}.tflite"
        header_path = f"{output_base}.h"

        add_log(f"\n导出TFLite模型: {tflite_path}")
        tflite_model = convert_to_tflite(model, tflite_path)
        size_kb = len(tflite_model) / 1024
        add_log(f"模型大小: {size_kb:.1f} KB")

        add_log(f"导出C头文件: {header_path}")
        tflite_to_c_array(list(tflite_model), header_path)

        np.savez(f"{output_base}_params.npz", 
                mean=scaler.mean_, 
                std=np.sqrt(scaler.var_),
                classes=np.array(unique_labels, dtype=object))

        add_log(f"\n✅ 全部完成！")
        add_log(f"  {tflite_path} - INT8量化模型")
        add_log(f"  {header_path} - Arduino C头文件，直接include使用")
        add_log(f"  {output_base}_params.npz - 参数信息")

        g_state["last_result"] = {
            "accuracy": float(test_acc),
            "size_kb": float(size_kb),
            "header_path": header_path,
            "tflite_path": tflite_path
        }

    except Exception as e:
        add_log(f"❌ 训练出错: {str(e)}")
        import traceback
        for line in traceback.format_exc().split('\n'):
            if line.strip():
                add_log(line)
    finally:
        g_state["training"] = False

@app.route('/api/train', methods=['POST'])
def api_train():
    params = request.get_json()
    threading.Thread(target=training_worker, args=(params,), daemon=True).start()
    return jsonify({"success": True})

if __name__ == "__main__":
    add_log("🚀 Web训练服务器启动，监听 0.0.0.0:5000")
    add_log("浏览器访问: http://<你的AX630C IP>:5000")
    add_log("内存占用低，适配1GB内存")
    app.run(host='0.0.0.0', port=5000, debug=False)
